from dataclasses import dataclass

import crypto
from framing import receive_frame, send_frame
from protocol import FrameType, Size


@dataclass
class SessionKeys:
    send_encryption_key: bytes
    receive_encryption_key: bytes
    send_mac_key: bytes
    receive_mac_key: bytes


class HandshakeError(Exception):
    """Raised when the handshake cannot be completed."""


# Handshake Client Side
def perform_client_handshake(sock):

    print("Generating ECDH Keys.......")
    private_key = crypto.generate_private_key()
    public_key = crypto.generate_public_key(private_key)
    public_key_bytes = crypto.serialize_key(public_key)

    # Send client public key
    print("Sending ECDH public key......")
    send_frame(
        sock,
        FrameType.HANDSHAKE,
        public_key_bytes,
    )

    # Receive server public key
    print("Receiving server ECDH public key......")
    frame = receive_frame(sock)

    if frame is None:
        raise HandshakeError("Connection closed during handshake")

    frame_type, peer_public_key_bytes = frame

    if frame_type != FrameType.HANDSHAKE:
        raise HandshakeError("Expected server public key during handshake")

    # Converting Binary to Ecdh object
    peer_public_key = crypto.deserialize_key(peer_public_key_bytes)

    # Deriving shared secret.
    shared_secret = crypto.derive_shared_secret(
        private_key,
        peer_public_key,
    )

    print("Shared secret derived.")

    # Client generates and sends the salt.
    salt = crypto.generate_salt()
    print("Sending Salt.....")
    send_frame(
        sock,
        FrameType.HANDSHAKE,
        salt,
    )

    (
        server_to_client_encryption_key,
        client_to_server_encryption_key,
        server_to_client_mac_key,
        client_to_server_mac_key,
    ) = crypto.derive_keys(
        salt,
        shared_secret,
    )

    # Validating Handshake using transcript
    print("Confirming Valid HANDSHAKE.........")

    # Both sides construct the same transcript.(client public || server public || salt)
    transcript = public_key_bytes + peer_public_key_bytes + salt

    # Proving server that client derived same keys.
    client_confirmation = crypto.compute_hmac(
        client_to_server_mac_key,
        transcript,
    )

    send_frame(
        sock,
        FrameType.HANDSHAKE_CONFIRM,
        client_confirmation,
    )

    # Verify server confirmation.
    frame = receive_frame(sock)

    if frame is None:
        raise HandshakeError("Connection closed during handshake confirmation")

    frame_type, server_confirmation = frame

    if frame_type == FrameType.QUIT:
        raise HandshakeError("Server rejected the handshake")

    if frame_type != FrameType.HANDSHAKE_CONFIRM:
        raise HandshakeError("Expected server handshake confirmation")

    # Verifying server had the same keys as client.
    expected_server_confirmation = crypto.compute_hmac(
        server_to_client_mac_key,
        transcript,
    )

    if not crypto.compare_hmac(
        server_confirmation,
        expected_server_confirmation,
    ):
        send_frame(
            sock,
            FrameType.QUIT,
            b"/quit",
        )
        raise HandshakeError("Server handshake confirmation failed")

    return SessionKeys(
        send_encryption_key=client_to_server_encryption_key,
        receive_encryption_key=server_to_client_encryption_key,
        send_mac_key=client_to_server_mac_key,
        receive_mac_key=server_to_client_mac_key,
    )


# Handshake Server side
def perform_server_handshake(sock):

    print("Generating ECDH Keys.......")
    private_key = crypto.generate_private_key()
    public_key = crypto.generate_public_key(private_key)
    public_key_bytes = crypto.serialize_key(public_key)

    # Receive client public key
    print("Receiving client ECDH public key......")
    frame = receive_frame(sock)

    if frame is None:
        raise HandshakeError("Connection closed during handshake")

    frame_type, peer_public_key_bytes = frame

    if frame_type != FrameType.HANDSHAKE:
        raise HandshakeError("Expected client public key during handshake")

    peer_public_key = crypto.deserialize_key(peer_public_key_bytes)

    # Send server public key
    print("Sending ECDH public key......")
    send_frame(
        sock,
        FrameType.HANDSHAKE,
        public_key_bytes,
    )

    # Derive shared secret
    print("Shared secret derived.")
    shared_secret = crypto.derive_shared_secret(
        private_key,
        peer_public_key,
    )

    # Receive salt generated by client
    frame = receive_frame(sock)
    print("Salt Received.")

    if frame is None:
        raise HandshakeError("Connection closed while receiving salt")

    frame_type, salt = frame

    if frame_type != FrameType.HANDSHAKE:
        raise HandshakeError("Expected salt during handshake")

    if len(salt) != Size.SALT_SIZE:
        raise HandshakeError("Invalid handshake salt length")

    (
        server_to_client_encryption_key,
        client_to_server_encryption_key,
        server_to_client_mac_key,
        client_to_server_mac_key,
    ) = crypto.derive_keys(
        salt,
        shared_secret,
    )

    # Validating Handshake using transcript
    print("Confirming Valid HANDSHAKE.........")

    # Both sides construct the same transcript.(client public || server public || salt)
    transcript = peer_public_key_bytes + public_key_bytes + salt

    # Verifying Client has same keys
    frame = receive_frame(sock)

    if frame is None:
        raise HandshakeError("Connection closed during handshake confirmation")

    frame_type, client_confirmation = frame

    if frame_type != FrameType.HANDSHAKE_CONFIRM:
        raise HandshakeError("Expected client handshake confirmation")

    expected_client_confirmation = crypto.compute_hmac(
        client_to_server_mac_key,
        transcript,
    )

    if not crypto.compare_hmac(
        client_confirmation,
        expected_client_confirmation,
    ):
        send_frame(
            sock,
            FrameType.QUIT,
            b"/quit",
        )

        raise HandshakeError("Client handshake confirmation failed")

    # Proving Client that server has same keys
    server_confirmation = crypto.compute_hmac(
        server_to_client_mac_key,
        transcript,
    )

    send_frame(
        sock,
        FrameType.HANDSHAKE_CONFIRM,
        server_confirmation,
    )

    return SessionKeys(
        send_encryption_key=server_to_client_encryption_key,
        receive_encryption_key=client_to_server_encryption_key,
        send_mac_key=server_to_client_mac_key,
        receive_mac_key=client_to_server_mac_key,
    )
